### ISSUE TITLE
[Addon: Van-DML] Cannot access file via cdn.jsdelivr.net

### ISSUE THREAD

**Issue by efpage** [vanjs-org/van#67] opened 2023-07-09 04:19 UTC
Files from github can be accessed via cdn like 

https://cdn.jsdelivr.net/gh/vanjs-org/van@latest/public/van-latest.nomodule.min.js

for some reason this does not work here:

https://cdn.jsdelivr.net/gh/vanjs-org/van@latest/addons/van_dml/src/van_dml.js

but direct acess is possible with this link

https://raw.githubusercontent.com/vanjs-org/van/main/addons/van_dml/src/van_dml.js

any hint welcome

**Comment by Tao-VanJS** [comment] 2023-07-09 20:56
The root cause is that Van-DML was merged after the latest VanJS release. I created a Van-DML specific release and the following link works now:

https://cdn.jsdelivr.net/gh/vanjs-org/van@Van-DML-0.1.0/addons/van_dml/src/van_dml.js

I'm expecting the link that points to the latest release will work soon.

**Comment by Tao-VanJS** [comment] 2023-07-12 08:45
Closing the issue as Van-DML is accessible via CDN.

**Closed by Tao-VanJS** 2023-07-12 08:45 UTC

**Comment by Tao-VanJS** [comment] 2023-07-17 03:31
The link https://cdn.jsdelivr.net/gh/vanjs-org/van@latest/addons/van_dml/src/van_dml.js works now :-)
